from app import db
import sqlalchemy
from app.rezept import Association, rezept, zutat,tags

tags.query.delete()
db.session.rollback()
def addTags(name):
    new = tags(name=name)
    db.session.add(new)
    db.session.commit()

db.session.commit()
addTags("Spargel-Kloss-Auflauf")
addTags("Fisch")
addTags("Einfaches Hackfleisch Gratin")
addTags("einfach")
addTags("schnell")
addTags("reicht fuer 6 Pizzen")
addTags("Gefuellte Kartoffeln")
addTags("schnelle Sache")
addTags("wie beim Italiener")
addTags("ohne Mehl")
addTags("keto-geeignet")
addTags("low carb und keto-geeignet")
addTags("leckeres Curry")
addTags("fuer Gaeste geeignet")
addTags("in Muffinfoermchen gebacken")
addTags("fuer jeden Gaumen")
addTags("ergibt 24 Stueck")
addTags("herzhafte Pfannkuchen")
addTags("ganz einfach und lecker")
addTags("schnell und lecker")
addTags("italienisches Rezept")
addTags("knusprig duenner Boden")
addTags("Gurken")
addTags("Senf und Speck")
addTags("Rikes Backschule - Kuchen")
addTags("die jeder mag")
addTags("fuer eine 26er Springform")
addTags("duenner")
addTags("knuspriger Teig ohne Hefe")
addTags("Hackfleisch Gratin")
addTags("schnelles")
addTags("Kartoffelnudel-Gratin")
addTags("unkompliziert")
addTags("vegan")
addTags("ideal fuer Gaeste")
addTags("gut fuer die grosse Runde")
addTags("ergibt ca. 7 Stueck")
addTags("mein Geheimrezept")
addTags("wirklich sehr lecker")
addTags("leicht und saftig")
addTags("Low carb")
addTags("Logi")
addTags("Montignac")
addTags("Low carb Rezept - ohne Teig")
addTags("low carb")
addTags("fettarm")
addTags("kalorienarm")
addTags("gesund")
addTags("vegetarisch")
addTags("megalecker und simpel")
addTags("prima Snack")
addTags("daenisches Biksemad")
addTags("Leckere Beilage zu Fleisch")
addTags("Gefluegel")
addTags("Cheeseburger")
addTags("herzhafte Muffins")
addTags("Party und Buffet Snacks")
addTags("dieses Huhn ist hot")
addTags("spicy")
addTags("indisch")
addTags("ein vegetarisches Gericht")
addTags("das einfach gluecklich macht")
addTags("einfach und lecker")
addTags("superschnell")
addTags("superlecker")
addTags("leckere Lasagne ohne Nudeln")
addTags("dann schmeckt es am besten")


rezaus = rezept.query.get(23)
taaus = tags.query.filter_by(name="Spargel-Kloss-Auflauf").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(24)
taaus = tags.query.filter_by(name="Fisch").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(29)
taaus = tags.query.filter_by(name="Einfaches Hackfleisch Gratin").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(30)
taaus = tags.query.filter_by(name="einfach").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(30)
taaus = tags.query.filter_by(name="schnell").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(34)
taaus = tags.query.filter_by(name="reicht fuer 6 Pizzen").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(36)
taaus = tags.query.filter_by(name="Gefuellte Kartoffeln").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(37)
taaus = tags.query.filter_by(name="schnelle Sache").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(37)
taaus = tags.query.filter_by(name="einfach").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(40)
taaus = tags.query.filter_by(name="wie beim Italiener").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(43)
taaus = tags.query.filter_by(name="ohne Mehl").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(43)
taaus = tags.query.filter_by(name="keto-geeignet").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(44)
taaus = tags.query.filter_by(name="ohne Mehl").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(44)
taaus = tags.query.filter_by(name="low carb und keto-geeignet").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(48)
taaus = tags.query.filter_by(name="leckeres Curry").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(49)
taaus = tags.query.filter_by(name="in Muffinfoermchen gebacken").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(61)
taaus = tags.query.filter_by(name="herzhafte Pfannkuchen").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(61)
taaus = tags.query.filter_by(name="ganz einfach und lecker").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(62)
taaus = tags.query.filter_by(name="einfach").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(62)
taaus = tags.query.filter_by(name="schnell und lecker").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(64)
taaus = tags.query.filter_by(name="italienisches Rezept").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(64)
taaus = tags.query.filter_by(name="knusprig duenner Boden").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(66)
taaus = tags.query.filter_by(name="Gurken").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(66)
taaus = tags.query.filter_by(name="Senf und Speck").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(68)
taaus = tags.query.filter_by(name="Rikes Backschule - Kuchen").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(68)
taaus = tags.query.filter_by(name="die jeder mag").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(70)
taaus = tags.query.filter_by(name="duenner").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(70)
taaus = tags.query.filter_by(name="knuspriger Teig ohne Hefe").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(72)
taaus = tags.query.filter_by(name="Hackfleisch Gratin").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(74)
taaus = tags.query.filter_by(name="schnelles").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(73)
taaus = tags.query.filter_by(name="Kartoffelnudel-Gratin").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(77)
taaus = tags.query.filter_by(name="unkompliziert").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(77)
taaus = tags.query.filter_by(name="vegan").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(81)
taaus = tags.query.filter_by(name="ideal fuer Gaeste").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(83)
taaus = tags.query.filter_by(name="gut fuer die grosse Runde").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(85)
taaus = tags.query.filter_by(name="mein Geheimrezept").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(85)
taaus = tags.query.filter_by(name="wirklich sehr lecker").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(87)
taaus = tags.query.filter_by(name="leicht und saftig").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(88)
taaus = tags.query.filter_by(name="Low carb").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(88)
taaus = tags.query.filter_by(name="Logi").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(88)
taaus = tags.query.filter_by(name="Montignac").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(89)
taaus = tags.query.filter_by(name="Low carb Rezept - ohne Teig").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(90)
taaus = tags.query.filter_by(name="low carb").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(90)
taaus = tags.query.filter_by(name="fettarm").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(90)
taaus = tags.query.filter_by(name="kalorienarm").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(90)
taaus = tags.query.filter_by(name="gesund").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(90)
taaus = tags.query.filter_by(name="vegetarisch").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(1)
taaus = tags.query.filter_by(name="schnell").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(1)
taaus = tags.query.filter_by(name="einfach").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(4)
taaus = tags.query.filter_by(name="megalecker und simpel").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(4)
taaus = tags.query.filter_by(name="prima Snack").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(5)
taaus = tags.query.filter_by(name="daenisches Biksemad").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(8)
taaus = tags.query.filter_by(name="Leckere Beilage zu Fleisch").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(8)
taaus = tags.query.filter_by(name="Fisch").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(8)
taaus = tags.query.filter_by(name="Gefluegel").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(9)
taaus = tags.query.filter_by(name="Cheeseburger").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(9)
taaus = tags.query.filter_by(name="herzhafte Muffins").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(9)
taaus = tags.query.filter_by(name="Party und Buffet Snacks").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(10)
taaus = tags.query.filter_by(name="dieses Huhn ist hot").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(10)
taaus = tags.query.filter_by(name="spicy").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(10)
taaus = tags.query.filter_by(name="indisch").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(11)
taaus = tags.query.filter_by(name="ein vegetarisches Gericht").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(11)
taaus = tags.query.filter_by(name="das einfach gluecklich macht").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(12)
taaus = tags.query.filter_by(name="einfach und lecker").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(17)
taaus = tags.query.filter_by(name="superschnell").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(17)
taaus = tags.query.filter_by(name="superlecker").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(17)
taaus = tags.query.filter_by(name="vegetarisch").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(18)
taaus = tags.query.filter_by(name="leckere Lasagne ohne Nudeln").first()
rezaus.tags.append(taaus)
rezaus = rezept.query.get(20)
taaus = tags.query.filter_by(name="dann schmeckt es am besten").first()
rezaus.tags.append(taaus)
db.session.commit()
