"""new db

Revision ID: 036290ae4cfe
Revises: 
Create Date: 2022-06-11 11:19:48.523179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036290ae4cfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlungsschritt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('bild2', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rezept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zutat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_rzhat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('zutat_id', sa.Integer(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.id'], ),
    sa.ForeignKeyConstraint(['zutat_id'], ['zutat.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_rzhat')
    op.drop_table('zutat')
    op.drop_table('rezept')
    op.drop_table('handlungsschritt')
    # ### end Alembic commands ###
