"""new

Revision ID: 08a0dfcec82b
Revises: 
Create Date: 2022-06-20 09:33:46.988158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a0dfcec82b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlungsschritt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('bild2', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('konto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rights', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rezept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zutat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_rhhat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('handlungsschrit_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['handlungsschrit_id'], ['handlungsschritt.id'], ),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.id'], )
    )
    op.create_table('association_rthat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], )
    )
    op.create_table('association_rzhat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('zutat_id', sa.Integer(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.Column('Menge', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.id'], ),
    sa.ForeignKeyConstraint(['zutat_id'], ['zutat.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_rzhat')
    op.drop_table('association_rthat')
    op.drop_table('association_rhhat')
    op.drop_table('zutat')
    op.drop_table('tags')
    op.drop_table('rezept')
    op.drop_table('konto')
    op.drop_table('handlungsschritt')
    # ### end Alembic commands ###
