"""empty message

Revision ID: 4853b5a0b1fd
Revises: 9c3a85cab770
Create Date: 2022-06-09 12:56:54.523257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4853b5a0b1fd'
down_revision = '9c3a85cab770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rzhat2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rzhat2',
    sa.Column('rezept_id', sa.INTEGER(), nullable=False),
    sa.Column('zutat_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.rid'], ),
    sa.ForeignKeyConstraint(['zutat_id'], ['zutat.zid'], ),
    sa.PrimaryKeyConstraint('rezept_id', 'zutat_id')
    )
    # ### end Alembic commands ###
