"""init

Revision ID: 714284f5fbcf
Revises: 
Create Date: 2022-07-06 13:29:45.735719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714284f5fbcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlungsschritt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('bild2', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rezeptsql',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zutatsql',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('zid', sa.Integer(), nullable=False),
    sa.Column('menge', sa.Integer(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rid'], ['rezeptsql.id'], ),
    sa.ForeignKeyConstraint(['zid'], ['zutatsql.id'], ),
    sa.PrimaryKeyConstraint('rid', 'zid')
    )
    op.create_table('association_rhhat',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('hid', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hid'], ['handlungsschritt.id'], ),
    sa.ForeignKeyConstraint(['rid'], ['rezeptsql.id'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('association_rthat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezeptsql.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_rthat')
    op.drop_table('association_rhhat')
    op.drop_table('association')
    op.drop_table('zutatsql')
    op.drop_table('tags')
    op.drop_table('rezeptsql')
    op.drop_table('handlungsschritt')
    # ### end Alembic commands ###
