"""2

Revision ID: 776532d39039
Revises: 036290ae4cfe
Create Date: 2022-06-12 21:19:41.196051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776532d39039'
down_revision = '036290ae4cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_rhhat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('handlungsschrit_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['handlungsschrit_id'], ['handlungsschritt.id'], ),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.id'], )
    )
    op.create_table('association_rthat',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], )
    )
    op.add_column('association_rzhat', sa.Column('Menge', sa.Boolean(), nullable=True))
    op.drop_column('rezept', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rezept', sa.Column('tags', sa.VARCHAR(), nullable=True))
    op.drop_column('association_rzhat', 'Menge')
    op.drop_table('association_rthat')
    op.drop_table('association_rhhat')
    op.drop_table('tags')
    # ### end Alembic commands ###
