"""Add new Column

Revision ID: 9c3a85cab770
Revises: 8de6da61d3e3
Create Date: 2022-06-09 10:25:36.835856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3a85cab770'
down_revision = '8de6da61d3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('zutat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.rid'], ),
    sa.ForeignKeyConstraint(['zutat_id'], ['zutat.zid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
