"""init

Revision ID: c1e5f326f3b3
Revises: 
Create Date: 2022-06-05 16:21:50.094926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e5f326f3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handlungsschritt',
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('bild2', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_table('rezept',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('zutat',
    sa.Column('zid', sa.Integer(), nullable=False),
    sa.Column('einheit', sa.String(), nullable=True),
    sa.Column('bild', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.rid'], ),
    sa.PrimaryKeyConstraint('zid')
    )
    op.create_table('association',
    sa.Column('rezept_id', sa.Integer(), nullable=True),
    sa.Column('zutat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rezept_id'], ['rezept.rid'], ),
    sa.ForeignKeyConstraint(['zutat_id'], ['zutat.zid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('zutat')
    op.drop_table('rezept')
    op.drop_table('handlungsschritt')
    # ### end Alembic commands ###
